language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed -f udagram-api-feed/Dockerfile udagram-api-feed
  - docker build -t udagram-api-user -f udagram-api-user/Dockerfile udagram-api-user
  - docker build -t udagram-frontend -f udagram-frontend/Dockerfile udagram-frontend
  - docker build -t reverseproxy -f reverseproxy/Dockerfile reverseproxy
  - docker tag udagram-api-feed dipti20/udagram-api-feed:latest
  - docker tag udagram-api-user dipti20/udagram-api-user:latest
  - docker tag udagram-frontend dipti20/udagram-frontend:latest
  - docker tag reverseproxy  dipti20/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dipti20/udagram-api-feed:latest
  - docker push dipti20/udagram-api-user:latest
  - docker push dipti20/udagram-frontend:latest
  - docker push dipti20/reverseproxy:latest
