apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: dipti20/udagram-api-user:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-config
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
          envFrom:
            - secretRef:
                name: env-secret
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "900m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
